# Generated by Django 2.2.13 on 2021-05-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('learning_unit', '0002_learningclassyear_changed'), ('learning_unit', '0003_centralmanager'), ('learning_unit', '0004_auto_20200618_1435'), ('learning_unit', '0005_role_migration_centralmanager_facultymanager'), ('learning_unit', '0006_auto_20210112_1041'), ('learning_unit', '0007_auto_20210118_1438'), ('learning_unit', '0006_auto_20210202_1029'), ('learning_unit', '0008_merge_20210203_1310'), ('learning_unit', '0009_auto_20210203_1310'), ('learning_unit', '0010_auto_20210115_1314'), ('learning_unit', '0011_auto_20210317_1559'), ('learning_unit', '0012_auto_20210318_1005')]

    dependencies = [
        ('learning_unit', '0001_initial'),
        ('base', '0515_auto_20200519_1649'),
        ('base', '0581_auto_20210317_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
            options={
                'verbose_name': 'Central manager',
                'verbose_name_plural': 'Central managers',
                'default_related_name': 'learning_unit',
            },
        ),
        migrations.CreateModel(
            name='FacultyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
            options={
                'verbose_name': 'Faculty manager',
                'verbose_name_plural': 'Faculty managers',
                'default_related_name': 'learning_unit',
            },
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
