# Generated by Django 2.2.13 on 2021-02-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0006_auto_20210202_1029'),
        ('learning_unit', '0007_auto_20210118_1438'),
    ]

    operations = [
    ]
