# Generated by Django 2.2.13 on 2021-02-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0008_merge_20210203_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
        migrations.AlterField(
            model_name='facultymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
    ]
