# Generated by Django 2.2.13 on 2021-02-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0008_merge_20210118_1639'),
        ('learning_unit', '0009_auto_20210203_1310'),
    ]

    operations = [
    ]
