# Generated by Django 2.2.13 on 2021-05-25 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0586_auto_20210510_1835'),
        ('learning_unit', '0012_auto_20210318_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningclassyear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Campus',
                                    verbose_name='Learning location'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='hourly_volume_partial_q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True,
                                      verbose_name='hourly volume partial q1'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='hourly_volume_partial_q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True,
                                      verbose_name='hourly volume partial q2'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='hourly_volume_total_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True,
                                      verbose_name='hourly volume total annual'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='quadrimester',
            field=models.CharField(blank=True,
                                   choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q1and2', 'Q1 and Q2'),
                                            ('Q1or2', 'Q1 or Q2')], max_length=9, null=True,
                                   verbose_name='Quadrimester'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='session',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('12', '12'), ('13', '13'),
                                                        ('23', '23'), ('123', '123'), ('P23', 'P23')], max_length=50,
                                   null=True, verbose_name='Session derogation'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title in English'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title in French'),
        ),
        migrations.AlterField(
            model_name='learningclassyear',
            name='acronym',
            field=models.CharField(max_length=1, validators=[
                django.core.validators.RegexValidator('^[a-zA-Z0-9]$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
