# Generated by Django 2.2.13 on 2021-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_unit', '0013_auto_20210525_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningclassyear',
            name='description',
        ),
        migrations.AlterField(
            model_name='learningclassyear',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title in English'),
        ),
    ]
