# Generated by Django 2.2.13 on 2021-07-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0006_auto_20210630_0911'),
        ('base', '0588_remove_learningcomponentyear_uuid'),
        ('assessments', '0001_squashed_0006_auto_20190802_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('attribution_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribution.AttributionChargeNew')),
                ('attribution_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribution.AttributionClass')),
                ('learning_unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear')),
            ],
        ),
    ]
