# Generated by Django 2.2.13 on 2021-06-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_squashed_0006_auto_20190802_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheetaddress',
            name='cohort_name',
            field=models.CharField(blank=True, choices=[('FIRST_YEAR', 'First year bachelor')], default=None, max_length=25, null=True, verbose_name='Cohort name'),
        ),
        migrations.AlterField(
            model_name='scoresheetaddress',
            name='education_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetaddress',
            constraint=models.UniqueConstraint(fields=('education_group', 'cohort_name'), name='unique_education_group_cohort_name'),
        ),
    ]
