# Generated by Django 2.2.13 on 2021-07-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0014_auto_20210604_1537'),
        ('base', '0592_auto_20210719_1125'),
        ('assessments', '0002_scoreresponsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreresponsible',
            name='attribution_charge',
        ),
        migrations.RemoveField(
            model_name='scoreresponsible',
            name='attribution_class',
        ),
        migrations.AddField(
            model_name='scoreresponsible',
            name='learning_class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_unit.LearningClassYear'),
        ),
        migrations.AddField(
            model_name='scoreresponsible',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Tutor'),
        ),
        migrations.AddConstraint(
            model_name='scoreresponsible',
            constraint=models.UniqueConstraint(fields=('learning_unit_year', 'learning_class_year'), name='unique_score_responsible'),
        ),
    ]
