# Generated by Django 2.2.13 on 2021-08-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20210720_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheetaddress',
            name='cohort_name',
            field=models.CharField(blank=True, choices=[('FIRST_YEAR', 'First year bachelor')], max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scoresheetaddress',
            name='education_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetaddress',
            constraint=models.UniqueConstraint(fields=('education_group', 'cohort_name'), name='unique_score_sheet_address'),
        ),
    ]
