# Generated by Django 2.2.13 on 2021-08-31 10:20

from django.db import migrations
from django.db.models import Prefetch, OuterRef, Exists

ACADEMIC_YEAR = 2021


def get_score_sheet_address_to_populate_cohort_name_field_queryset(apps):
    EducationGroupYear = apps.get_model("base", "EducationGroupYear")
    ScoreSheetAddress = apps.get_model("assessments", "ScoreSheetAddress")

    education_group_year_subqs = EducationGroupYear.objects.filter(
        academic_year__year=ACADEMIC_YEAR,
        acronym__icontains="11BA",
        education_group=OuterRef("education_group")
    )
    return ScoreSheetAddress.objects.annotate(
        of_first_year_bachelor=Exists(education_group_year_subqs)
    ).filter(
        of_first_year_bachelor=True
    )


def fill_cohort_field(address):
    address.cohort_name = "FIRST_YEAR"
    address.save()


def populate_cohort_field(apps, schema_editor):
    print("Fill cohort field of score sheet addresses")
    addresses_to_fill_cohort = get_score_sheet_address_to_populate_cohort_name_field_queryset(apps)
    for address in addresses_to_fill_cohort:
        fill_cohort_field(address)
        print("- {}".format(address.id))


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_scoresheetaddress_entity'),
    ]

    operations = [
        migrations.RunPython(
            populate_cohort_field
        ),
    ]
