# Generated by Django 2.2.13 on 2021-06-01 06:20

from django.db import migrations

from education_group.models.enums.cohort_name import CohortName

BAC_CODE = '1BA'
OLD_BAC_CODE = '11BA'


def migrate_score_sheet_address_11ba_to_1BA(apps, shema_editor):
    ScoreSheetAddress = apps.get_model('assessments', 'scoresheetaddress')
    EducationGroupYear = apps.get_model('base', 'educationgroupyear')

    education_group_years = EducationGroupYear.objects.filter(acronym__contains=OLD_BAC_CODE)
    for elem in education_group_years:
        old_score_sheet_address = ScoreSheetAddress.objects.get(education_group=elem.education_group)
        new_score_sheet_address = old_score_sheet_address
        print(str(old_score_sheet_address)+" ------------------- "+str(new_score_sheet_address))
        acronym_patern = elem.acronym.replace(OLD_BAC_CODE, BAC_CODE)
        education_group_year = EducationGroupYear.objects.filter(acronym=acronym_patern).last()
        if old_score_sheet_address:
            new_score_sheet_address.id = None
            new_score_sheet_address.pk = None
            new_score_sheet_address.external_id = None
            new_score_sheet_address.education_group = education_group_year.education_group
            new_score_sheet_address.cohort_name = CohortName.FIRST_YEAR.name
            new_score_sheet_address.save()
            old_score_sheet_address.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20210609_1439'),
    ]

    operations = [
        migrations.RunPython(migrate_score_sheet_address_11ba_to_1BA),
    ]
