# Generated by Django 2.2.13 on 2021-09-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_populate_entity_cohort_of_score_sheet_address'),
    ]

    operations = [

    ]
