# Generated by Django 2.2.13 on 2021-09-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_history', '0002_historyentry_tags'),
        ('assessments', '0007_populate_score_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [],
                'indexes': [],
            },
            bases=('osis_history.historyentry',),
        ),
    ]
