# Generated by Django 2.2.13 on 2021-02-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_email_soumission'),
    ]

    operations = [
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
               {% autoescape off %}
                 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                 <h3>Correction de l'encodage de notes</h3>
                 <p>Bonjour,</p>
                 <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                 <p>Nous vous informons que des notes de {unite_enseignement} pour la formation {cohorte} ont été corrigées par le gestionnaire de parcours étudiant. Ces notes sont surlignées en vert.</p>
           
                 <p>{{ enrollments }}</p>
                 
                 <p>{{ signature }}</p>

               {% endautoescape off %}
               ''',
               "Correction de l'encodage complet des notes de {unite_enseignement} pour {cohorte}",
               'assessments_correction_encodage_complet_html',
               'HTML',
               'fr-be'])], elidable=True
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
               {% autoescape off %}
                 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                 <h3>Correction de l'encodage de notes</h3>
                 <p>Bonjour,</p>
                 <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                 <p>Nous vous informons que des notes de {unite_enseignement} pour la formation {cohorte} ont été corrigées par le gestionnaire de parcours étudiant. Ces notes sont surlignées en vert.</p>
           
                 <p>{{ enrollments }}</p>
                 
                 <p>{{ signature }}</p>

               {% endautoescape off %}
               ''',
               "Correction de l'encodage complet des notes de {unite_enseignement} pour {cohorte}",
               'assessments_correction_encodage_complet_txt',
               'PLAIN',
               'fr-be'])], elidable=True
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language)"
              " VALUES(%s, %s, %s ,%s ,%s);",
              ['''
               {% autoescape off %}
                 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                 <h3>Correction of the complete encoding</h3>
                 <p>Hello,</p>
                 <p>This is an automatic message generated by the OSIS server &ndash; Please do not reply to this message.</p>
                 <p>We inform you that scores of We inform you that scores of {unite_enseignement} for {cohorte} have been corrected by the program manager. These scores are highlighted in green. for ARKE11BA have been corrected by the program manager. These scores are highlighted in green.</p>
           
                 <p>{{ enrollments }}</p>
                 
                 <p>{{ signature }}</p>

               {% endautoescape off %}
               ''',
               'Correction of the complete encoding of {unite_enseignement} for {cohorte}',
               'assessments_correction_encodage_complet_html',
               'HTML',
               'en'])], elidable=True
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
               {% autoescape off %}
                 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                 <h3>Correction of the complete encoding</h3>
                 <p>Hello,</p>
                 <p>This is an automatic message generated by the OSIS server &ndash; Please do not reply to this message.</p>
                 <p>We inform you that scores of We inform you that scores of {unite_enseignement} for {cohorte} have been corrected by the program manager. These scores are highlighted in green. for ARKE11BA have been corrected by the program manager. These scores are highlighted in green.</p>
           
                 <p>{{ enrollments }}</p>
                 
                 <p>{{ signature }}</p>

               {% endautoescape off %}
               ''',
               'Correction of the complete encoding of {unite_enseignement} for {cohorte}',
               'assessments_correction_encodage_complet_txt',
               'PLAIN',
               'en'])], elidable=True
        ),
    ]
