# Generated by Django 2.2.13 on 2021-10-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_fix_populate_score_responsible'),
        ('assessments', '0010_correct_address_11ba'),
    ]

    operations = [
    ]
