# Generated by Django 2.2.13 on 2021-10-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_merge_20211007_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresheetaddress',
            name='entity',
        ),
    ]
