# Generated by Django 2.2.13 on 2021-05-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('education_group', '0003_groupyear_academic_year'), ('education_group', '0004_groupyear_management_entity'), ('education_group', '0005_auto_20200128_1246')]

    dependencies = [
        ('base', '0497_auto_20200108_1213'),
        ('education_group', '0002_auto_20191224_1144'),
        ('base', '0489_auto_20191217_1505'),
    ]

    operations = [
    ]
