# Generated by Django 2.2.13 on 2021-05-28 06:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import education_group.auth.roles.utils


class Migration(migrations.Migration):

    replaces = [('education_group', '0006_centraladmissionmanager_centralmanager_facultymanager'), ('education_group', '0007_auto_20200416_1234'), ('education_group', '0008_auto_20200618_1628'), ('education_group', '0009_remove_groupyear_active'), ('education_group', '0010_auto_20201019_1604'), ('education_group', '0011_auto_20201007_0951'), ('education_group', '0012_copy_title_english_from_egy_to_gy'), ('education_group', '0013_auto_20210104_1024'), ('education_group', '0014_auto_20210112_0814'), ('education_group', '0015_auto_20210118_1043'), ('education_group', '0016_auto_20210129_0901'), ('education_group', '0016_auto_20210126_0836'), ('education_group', '0017_merge_20210129_1507'), ('education_group', '0015_auto_20210202_1029'), ('education_group', '0018_merge_20210203_1310'), ('education_group', '0019_auto_20210203_1310'), ('education_group', '0020_default_titles_and_credits'), ('education_group', '0021_default_titles_bis')]

    dependencies = [
        ('base', '0516_auto_20200602_1440'),
        ('base', '0511_auto_20200416_1234'),
        ('base', '0541_auto_20201019_1604'),
        ('education_group', '0005_auto_20200128_1246'),
        ('base', '0510_auto_20200408_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralAdmissionManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
            options={
                'verbose_name': 'Central admission manager',
                'verbose_name_plural': 'Central admission manager',
            },
        ),
        migrations.CreateModel(
            name='CentralManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ALL', 'ALL'), ('IUFC', 'IUFC'), ('DOCTORAT', 'DOCTORAT')], max_length=200), blank=True, size=None)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
            options={
                'verbose_name': 'Central manager',
                'verbose_name_plural': 'Central managers',
            },
            bases=(education_group.auth.roles.utils.EducationGroupTypeScopeRoleMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FacultyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ALL', 'ALL'), ('IUFC', 'IUFC'), ('DOCTORAT', 'DOCTORAT')], max_length=200), blank=True, size=None)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
            options={
                'verbose_name': 'Faculty manager',
                'verbose_name_plural': 'Faculty managers',
            },
            bases=(education_group.auth.roles.utils.EducationGroupTypeScopeRoleMixin, models.Model),
        ),
    ]
