# Generated by Django 2.2.13 on 2021-02-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0017_merge_20210129_1507'),
        ('education_group', '0015_auto_20210202_1029'),
    ]

    operations = [
    ]
