# Generated by Django 2.2.13 on 2021-05-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0586_auto_20210510_1835'),
        ('education_group', '0021_default_titles_bis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYearBachelor',
            fields=[
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('education_group_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.EducationGroupYear', verbose_name='Training')),
                ('administration_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_year_administration_entity', to='base.Entity', verbose_name='Administration entity')),
            ],
        ),
    ]
