# Generated by Django 2.2.13 on 2021-05-12 09:06

from django.db import migrations

from django.db.models import F
from django.utils import timezone

CONCERNED_GROUP_YEAR_TYPES = [
    'GROUP',
    'MINI_TRAINING',
    'TRAINING'
]


def clean_start_years(apps, schema_editor):
    clean_groups(apps)


def clean_groups(apps):
    problematic_gys = find_problematic_gys(apps)
    print("Problematic GroupYears: {}".format(len(problematic_gys)))
    group_to_update = []
    for gy in problematic_gys:
        print(
            "Group Year {} : changing start year from {} to {}".format(
                gy.partial_acronym,
                gy.group.start_year.year,
                gy.academic_year.year
            )
        )
        gy.group.start_year_id = gy.academic_year_id
        gy.group.changed = timezone.now()
        group_to_update.append(gy.group)
    Group = apps.get_model('education_group', 'Group')
    Group.objects.bulk_update(group_to_update, ['start_year_id', 'changed'], batch_size=1000)


def find_problematic_gys(apps):
    GroupYear = apps.get_model('education_group', 'GroupYear')
    return GroupYear.objects.filter(
        group__start_year__year__gt=F('academic_year__year'),
        education_group_type__category__in=CONCERNED_GROUP_YEAR_TYPES
    ).order_by(
        'group_id',
        'academic_year__year'
    ).distinct('group_id')


class Migration(migrations.Migration):
    dependencies = [
        ('education_group', '0021_default_titles_bis'),
    ]

    operations = [
        migrations.RunPython(clean_start_years),
    ]
