# Generated by Django 2.2.13 on 2021-05-31 09:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0586_auto_20210510_1835'),
        ('education_group', '0021_default_titles_bis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(choices=[('FIRST_YEAR', 'First year bachelor')], default='FIRST_YEAR', max_length=25, verbose_name='Name')),
                ('administration_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohort_year_administration_entity', to='base.Entity', verbose_name='Administration entity')),
                ('education_group_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroupYear', verbose_name='Training')),
            ],
            options={
                'verbose_name': 'Cohort year',
            },
        ),
        migrations.AddConstraint(
            model_name='cohortyear',
            constraint=models.UniqueConstraint(fields=('education_group_year', 'name'), name='unique_education_group_year_cohort'),
        ),
    ]
