# Generated by Django 2.2.13 on 2021-05-28 08:59

import base.models.enums.education_group_types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0022_firstyearbachelor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstyearbachelor',
            options={'verbose_name': 'First year bachelor'},
        ),
        migrations.AddConstraint(
            model_name='firstyearbachelor',
            constraint=models.CheckConstraint(check=models.Q(education_group_year__education_group_type__name=base.models.enums.education_group_types.TrainingType('Bachelor')), name='bachelor_type'),
        ),
    ]
