# Generated by Django 2.2.13 on 2021-06-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_auto_20210111_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeType',
        ),
        migrations.RemoveField(
            model_name='decree',
            name='uuid',
        )
    ]
