# Generated by Django 2.2.13 on 2021-08-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference', '0006_auto_20210623_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
