# Generated by Django 2.2.13 on 2021-08-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_auto_20210803_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('country',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
            ],
            options={
                'ordering': ('zip_code',),
            },
        ),
    ]
