# Generated by Django 2.2.13 on 2021-10-25 12:39

from django.db import migrations, models

CODE_NAME_EN_MAP = {
    'AR': 'Arabic',
    'CA': 'Catalan',
    'CS': 'Czech',
    'DA': 'Danish',
    'DE': 'German',
    'EL': 'Greek',
    'EN': 'English',
    'ES': 'Spanish',
    'FI': 'Finnish',
    'FR': 'French',
    'GA': 'Irish',
    'GL': 'Galician',
    'HE': 'Hebrew',
    'HI': 'Hindi',
    'HR': 'Croatian',
    'HU': 'Hungarian',
    'HY': 'Armenian',
    'IT': 'Italian',
    'JA': 'Japanese',
    'KA': 'Georgian',
    'KO': 'Korean',
    'LA': 'Latin',
    'LN': 'Lingala',
    'NL': 'Dutch',
    'NO': 'Norwegian',
    'PL': 'Polish',
    'PT': 'Portuguese',
    'QU': 'Quechua',
    'RO': 'Romanian',
    'RU': 'Russian',
    'SL': 'Slovenian',
    'SR': 'Serbian',
    'SV': 'Swedish',
    'SW': 'Swahili',
    'TR': 'Turkish',
    'UK': 'Ukrainian',
    'ZH': 'Chinese'
}


def fill_language_name_en(apps, schema_editor):
    Language = apps.get_model("reference", "Language")
    languages = Language.objects.all()

    fix_japanese_iso_code(languages)

    to_update = []
    for lang in languages:
        name_en = get_language_english_name(lang)
        if name_en:
            print("==== Add name_en {} to language {} (code {})".format(name_en, lang.name, lang.code))
            lang.name_en = name_en
            to_update.append(lang)
        else:
            print("==== Language {} : cannot get name in english".format(lang.name))
    Language.objects.bulk_update(to_update, ['name_en'], batch_size=1000)


def get_language_english_name(lang):
    if lang.code in ['??', 'XX']:
        # ?? = Language des signes en Belgique
        # XX = Indéterminé
        return 'Belgian Sign Language' if lang.code == '??' else 'Undetermined'
    else:
        return CODE_NAME_EN_MAP.get(lang.code)


def fix_japanese_iso_code(languages):
    japanese = languages.filter(code='JP')
    if japanese:
        japanese = japanese.first()
        japanese.code = 'JA'
        japanese.save()


class Migration(migrations.Migration):
    dependencies = [
        ('reference', '0008_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(fill_language_name_en)
    ]
