# Generated by Django 2.2.24 on 2022-01-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0621_merge_20220120_1018'),
        ('reference', '0009_auto_20211025_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(default='', max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, default='', max_length=30)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('linguistic_regime', models.ForeignKey(blank=True, limit_choices_to={'code__in': ['FR', 'NL']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('organization', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Organization')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.ZipCode')),
            ],
            options={
                'ordering': ('organization',),
            },
        ),
    ]
