# Generated by Django 2.2.24 on 2022-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_highschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='dialing_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
