openapi: 3.0.0
servers:
 - url: https://{environment}.osis.uclouvain.be/api/v1/reference/
   variables:
     environment:
       default: dev
       enum:
         - dev # Development server
         - qa # Staging server
         - test # Test server
 - url: https://osis.uclouvain.be/api/v1/reference/
   description: Production server
info:
  version: '1.10'
  title: Reference Service
  description: |-
    A set of API endpoints that allow you to get reference data.
paths:
  /countries/:
    get:
      description: Return a list of countries with optional filtering.
      operationId: countries_list
      parameters:
      - in: query
        name: limit
        schema:
          description: Number of results to return per page.
          type: integer
      - in: query
        name: offset
        schema:
          description: The initial index from which to return the results.
          type: integer
      - in: query
        name: search
        schema:
          description: A search term which will look up at country name
          type: string
      - in: query
        name: iso_code
        schema:
          description: Search by ISO 3166-1 2-letter country code
          type: string
      - in: query
        name: name
        schema:
          description: Search by country name. It can be partial/full name
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCountry'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      tags:
      - countries
  /countries/{uuid}:
    get:
      description: Return the detail of country
      operationId: countries_read
      parameters:
      - in: path
        name: uuid
        required: true
        schema:
          description: Universal unique identifier in version 4
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - countries
  /study-domains/:
    get:
      description: Return a list of study domains. By default, it will return all official main study domains.
      operationId: study_domains_list
      parameters:
        - in: query
          name: limit
          schema:
            description: Number of results to return per page.
            type: integer
        - in: query
          name: offset
          schema:
            description: The initial index from which to return the results.
            type: integer
        - in: query
          name: search
          schema:
            description: A search term which will look up at study domain name
            type: string
        - in: query
          name: decree
          schema:
            description: Filter on a specific decree
            type: string
            enum:
              - 'BEFORE_BOLOGNE'
              - 'BOLOGNE'
              - 'PAYSAGE'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfStudyDomain'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      tags:
        - study-domains
components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **Token &lt;token>**
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    ArrayOfCountry:
      type: array
      items:
        $ref: '#/components/schemas/Country'
    Country:
      type: object
      properties:
        url:
          type: string
          format: uri
        iso_code:
          type: string
          description: |
            The country code according to ISO 3166-1 specification
        name:
          type: string
          description: The name of the country
    ArrayOfStudyDomain:
      type: array
      items:
        $ref: '#/components/schemas/StudyDomain'
    StudyDomain:
      type: object
      properties:
        uuid:
          type: string
          description: The identifier of study domain
        code:
          type: string
          description: The code of study domain
        name:
          type: string
          description: The name of study domain
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
security:
  - Token: []