# Generated by Django 2.2.13 on 2021-06-17 17:26
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0002_auto_20210615_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
