# Generated by Django 2.2.13 on 2021-06-29 11:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_unit', '0014_auto_20210604_1537'),
        ('attribution', '0002_auto_20210615_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionnew',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='AttributionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('allocation_charge', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True,
                                                          validators=[django.core.validators.MinValueValidator(0)])),
                ('attribution_charge',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribution.AttributionChargeNew')),
                ('learning_class_year',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_unit.LearningClassYear')),
            ],
        ),
    ]
