# Generated by Django 2.2.13 on 2021-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0005_auto_20210617_1727'),
        ('attribution', '0002_attributionnew_uuid_and_attributionclass'),
    ]

    operations = [
    ]
