# Generated by Django 2.2.13 on 2021-08-19 10:15

from django.db import migrations
from django.utils import timezone

from base.models.enums.learning_container_year_types import COURSE
from base.models.enums.learning_unit_year_subtypes import PARTIM
from django.db.models import Q


def update_attribution_start_end_year(apps, schema_editor):
    AttributionChargeNew = apps.get_model('attribution', 'attributionchargenew')
    AttributionNew = apps.get_model('attribution', 'attributionnew')

    filter_type = \
        Q(learning_component_year__learning_unit_year__subtype=PARTIM) | \
        ~Q(attribution__learning_container_year__container_type=COURSE)

    attribution_charge_news = AttributionChargeNew.objects\
        .filter(
            attribution__start_year__isnull=True,
            attribution__end_year__isnull=True)\
        .filter(filter_type)

    attributions = []
    for attribution_charge_new in attribution_charge_news:
        year = attribution_charge_new.learning_component_year.learning_unit_year.academic_year.year
        attribution_charge_new.attribution.start_year = year
        attribution_charge_new.attribution.end_year = year
        attribution_charge_new.attribution.changed = timezone.now()
        attributions.append(attribution_charge_new.attribution)
    AttributionNew.objects.bulk_update(attributions, ['start_year', 'end_year', 'changed'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0006_auto_20210630_0911'),
    ]

    operations = [
        migrations.RunPython(update_attribution_start_end_year, migrations.RunPython.noop, elidable=True),
    ]
