# Generated by Django 2.2.13 on 2021-08-19 10:15

from django.db import migrations

from base.models.enums.learning_container_year_types import COURSE
from base.models.enums.learning_unit_year_subtypes import PARTIM


def update_year(attribution_charge_new, year: int):
    attribution_charge_new.attribution.start_year = year
    attribution_charge_new.attribution.end_year = year
    attribution_charge_new.save()


def update_attribution_start_end_year(apps, shema_editor):
    AttributionChargeNew = apps.get_model('attribution', 'attributionchargenew')

    qs = AttributionChargeNew.objects\
        .filter(
            attribution__start_year__isnull=True,
            attribution__end_year__isnull=True,
            learning_component_year__learning_unit_year__subtype=PARTIM
        ).exclude(attribution__learning_container_year__container_type=COURSE)

    for attribution_charge_new in qs:
        update_year(
            attribution_charge_new,
            attribution_charge_new.learning_component_year.learning_unit_year.academic_year.year
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0006_auto_20210630_0911'),
    ]

    operations = [
        migrations.RunPython(update_attribution_start_end_year, migrations.RunPython.noop, elidable=True),
    ]





