# Generated by Django 2.2.13 on 2021-10-07 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0007_initialize_attribution_start_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributionchargenew',
            name='allocation_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attributionclass',
            name='allocation_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
