# Generated by Django 2.2.13 on 2021-09-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0007_initialize_attribution_start_end_year'),
    ]

    operations = [
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template = %s WHERE reference='applications_confirmation_txt'; ",
                ['''
                    {% autoescape off %}
                        <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                        <p>A l'attention de {{first_name}} {{last_name}}.</p>
                        <p>Nous accusons réception de vo(tre)s candidature(s) aux cours suivants :</p>
                        <p>- directement via votre bureau, pour la (les) charge(s) suivante(s) :</p>
                        <p>{{applications}}</p>
                    
                        <p>Un accusé de réception définitif vous sera transmis à la fin de la période de candidature.</p>
                        <p>La publication des candidatures retenues est prévue pour le mois de mai {{application_courses_targeted_year}} sur le site de l'UCL.</p>
                     {% endautoescape off %}
                    '''])],
        ),
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template = %s WHERE reference='applications_confirmation_html'; ",
              ['''
                    {% autoescape off %}
                       <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                       <p>A l'attention de {{first_name}} {{last_name}}.</p>
                       <p>Nous accusons réception de vo(tre)s candidature(s) aux cours suivants :</p>
                       <p>- directement via votre bureau, pour la (les) charge(s) suivante(s) :</p>
                       <p>{{applications}}</p>
                    
                       <p>Un accusé de réception définitif vous sera transmis à la fin de la période de candidature.</p>
                       <p>La publication des candidatures retenues est prévue pour le mois de mai {{application_courses_targeted_year}} sur le site de l'UCL.</p>
                    {% endautoescape off %}
                    '''])],
        ),
    ]
