# Generated by Django 2.2.13 on 2021-09-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0008_auto_20210917_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorapplication',
            name='function',
        ),
    ]
