# Generated by Django 2.2.13 on 2021-10-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0008_auto_20211007_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribution',
        ),
    ]
