# Generated by Django 2.2.24 on 2022-01-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0010_auto_20211117_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tutor'),
        ),
    ]
