# Generated by Django 2.2.24 on 2022-01-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0012_auto_20220106_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorapplication',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
    ]
