# Generated by Django 2.2.24 on 2022-01-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0013_auto_20220106_0904'),
        ('attribution', '0011_auto_20220105_1305'),
    ]

    operations = [
    ]
