# Generated by Django 2.2.24 on 2021-11-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0014_merge_20220106_1142'),
    ]

    operations = [
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                        {% autoescape off %}
                            <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                            <p>A l'attention de {{first_name}} {{last_name}}.</p>
                            <br>
                            <p>Nous attirons votre attention sur le fait que certaines de vos charges arrivent à échéance :</p>
                            <p>{{ending_attributions}}</p>
                            <br>
                            <p>Le dépôt des candidatures aux cours vacants est possible jusqu’au {{end_date}}, pour plus 
                            d’informations : <a href="https://uclouvain.be/fr/decouvrir/cours-vacants.html">https://uclouvain.be/fr/decouvrir/cours-vacants.html</a></p>
                            <br>
                            <p>Evelyne Léonard</p>
                            <p>Vice-rectrice à la politique du personnel</p>  
                        {% endautoescape off %}
                        ''',
               'Charges d&#39;enseignement arrivant &agrave; &eacute;ch&eacute;ance',
               'ending_attributions_txt',
               'PLAIN',
               'fr-be'])],
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                           {% autoescape off %}
                            <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                            <p>A l'attention de {{first_name}} {{last_name}}.</p>
                            <br>
                            <p>Nous attirons votre attention sur le fait que certaines de vos charges arrivent à échéance :</p>
                            <p>{{ending_attributions}}</p>
                            <br>
                            <p>Le dépôt des candidatures aux cours vacants est possible jusqu’au {{end_date}}, pour plus 
                            d’informations : <a href="https://uclouvain.be/fr/decouvrir/cours-vacants.html">https://uclouvain.be/fr/decouvrir/cours-vacants.html</a></p>
                            <br>
                            <p>Evelyne Léonard</p>
                            <p>Vice-rectrice à la politique du personnel</p>                     
                            {% endautoescape off %}
                           ''',
               'Charges d&#39;enseignement arrivant &agrave; &eacute;ch&eacute;ance',
               'ending_attributions_html',
               'HTML',
               'fr-be'])],
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                    {% autoescape off %}
                        <p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>
                        <p>To the attention of {{first_name}} {{last_name}}.</p>
                        <br>
                        <p>We draw your attention on the fact that some of your attributions are about to expired:</p>
                        <p>{{ending_attributions}}</p>
                        <br>
                        <p>The closing date for submission of applications is the {{end_date}}. For more information, : <a href="https://uclouvain.be/fr/decouvrir/cours-vacants.html">https://uclouvain.be/fr/decouvrir/cours-vacants.html</a></p>
                        <br>
                        <p>Evelyne Léonard</p>
                        <p>Vice-Rector for Staff Policy</p>  
                    {% endautoescape off %}
                    ''',
               'Attributions about to expired',
               'ending_attributions_txt',
               'PLAIN',
               'en'])],
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                       {% autoescape off %}
                        <p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>
                        <p>To the attention of {{first_name}} {{last_name}}.</p>
                        <br>
                        <p>We draw your attention on the fact that some of your attributions are about to expired:</p>
                        <p>{{ending_attributions}}</p>
                        <br>
                        <p>The closing date for submission of applications is the {{end_date}}. For more information, : <a href="https://uclouvain.be/fr/decouvrir/cours-vacants.html">https://uclouvain.be/fr/decouvrir/cours-vacants.html</a></p>
                        <br>
                        <p>Evelyne Léonard</p>
                        <p>Vice-Rector for Staff Policy</p>                     
                        {% endautoescape off %}
                       ''',
               'Attributions about to expired',
               'ending_attributions_html',
               'HTML',
               'en'])],
        ),
    ]
