# Generated by Django 2.2.24 on 2022-01-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0015_auto_20220112_1126'),
        ('attribution', '0015_message_template_attributions_to_expired'),
    ]

    operations = [
    ]
