# Generated by Django 2.2.24 on 2022-01-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0016_merge_20220119_0924'),
    ]

    operations = [
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template = %s, subject = %s  WHERE reference='ending_attributions_txt'; ",
              ['''
                           {% autoescape off %}
                               <p><em>Ceci est un message automatique g&eacute;n&eacute;r&eacute; par le serveur OSIS &ndash; Merci de ne pas y r&eacute;pondre.</em></p>
                               <p>A l&#39;attention de {{first_name}} {{last_name}}.</p>
                               <br/>
                               <p>Nous attirons votre attention sur le fait que les charges de certains de vos cours arrivent &agrave; &eacute;ch&eacute;ance :</p>
                               <p>{{ending_attributions}}</p>
                               <br/>
                               <p>Le d&eacute;p&ocirc;t des candidatures aux cours vacants est possible jusqu’au {{end_date}}, pour plus 
                               d&#39;informations : <a href="https://uclouvain.be/fr/decouvrir/cours-vacants.html">https://uclouvain.be/fr/decouvrir/cours-vacants.html</a></p> 
                           {% endautoescape off %}
                           ''',
               'Charges d&#39;enseignement de vos cours arrivant &agrave; &eacute;ch&eacute;ance'
               ])],
        ),
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template = %s, subject = %s  WHERE reference='ending_attributions_html';",
              ['''
                              {% autoescape off %}
                               <p><em>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</em></p>
                               <p>A l'attention de {{first_name}} {{last_name}}.</p>
                               <br>
                               <p>Nous attirons votre attention sur le fait que les charges de certains de vos cours arrivent à échéance :</p>
                               <p>{{ending_attributions}}</p>
                               <br>
                               <p>Le dépôt des candidatures aux cours vacants est possible jusqu’au {{end_date}}, pour plus 
                               d’informations : <a href="https://uclouvain.be/fr/decouvrir/cours-vacants.html">https://uclouvain.be/fr/decouvrir/cours-vacants.html</a></p>
                               {% endautoescape off %}
                              ''',
               'Charges d&#39;enseignement de vos cours arrivant &agrave; &eacute;ch&eacute;ance'
               ])],
        ),
    ]
