# Generated by Django 2.2.13 on 2021-05-31 11:52
import uuid
from django.db import migrations


def tutorapplication_uuid(apps, schema_editor):
    TutorApplication = apps.get_model('attribution', 'TutorApplication')
    for row in TutorApplication.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0046_tutorapplication_uuid'),
    ]

    operations = [
        migrations.RunPython(tutorapplication_uuid, reverse_code=migrations.RunPython.noop),
    ]
