# Generated by Django 2.2.13 on 2021-05-31 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0047_auto_20210531_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
