# Generated by Django 2.2.13 on 2021-06-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0048_auto_20210531_1156'),
    ]

    operations = [
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                    {% autoescape off %}
                        <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                        <p>A l'attention de {{first_name}} {{last_name}}.</p>
                        <p>Nous accusons réception de vo(tre)s candidature(s) aux cours suivants :</p>
                        <p>- directement via votre bureau, pour la (les) charge(s) suivante(s) :</p>
                        <p>{{applications}}</p>
                        
                        <p>Un accusé de réception définitif vous sera transmis à la fin de la période de candidature.</p>
                        <p>La publication des candidatures retenues est prévue pour le mois de mai {{application_courses_targeted_year}} sur le site de l'UCL.</p>
                        <p>Evelyne Léonard</p>
                        <p>Vice-rectrice à la politique du personnel</p>                        
                     {% endautoescape off %}
                    ''',
               'Candidatures en ligne aux charges d&#39;enseignement : accus&eacute; de r&eacute;ception',
               'applications_confirmation_txt',
               'PLAIN',
               'fr-be'])],
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                       {% autoescape off %}
                           <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                           <p>A l'attention de {{first_name}} {{last_name}}.</p>
                           <p>Nous accusons réception de vo(tre)s candidature(s) aux cours suivants :</p>
                           <p>- directement via votre bureau, pour la (les) charge(s) suivante(s) :</p>
                           <p>{{applications}}</p>

                           <p>Un accusé de réception définitif vous sera transmis à la fin de la période de candidature.</p>
                           <p>La publication des candidatures retenues est prévue pour le mois de mai {{application_courses_targeted_year}} sur le site de l'UCL.</p>
                           <p>Evelyne Léonard</p>
                           <p>Vice-rectrice à la politique du personnel</p>                        
                        {% endautoescape off %}
                       ''',
               'Candidatures en ligne aux charges d&#39;enseignement : accus&eacute; de r&eacute;ception',
               'applications_confirmation_html',
               'HTML',
               'fr-be'])],
        ),
    ]
