openapi: 3.0.0
servers:
 - url: https://{environment}.osis.uclouvain.be/api/v1/learning_unit_enrollment/
   variables:
     environment:
       default: dev
       enum:
         - dev # Development server
         - qa # Staging server
         - test # Test server
 - url: https://osis.uclouvain.be/api/v1/learning_unit_enrollment/
   description: 'Production server'
info:
  version: '1.0'
  title: 'Learning Unit Enrollment Service'
  description: |-
    A set of API endpoints that allow you to get information about learning unit enrollment
paths:
  /enrollments/{acronym}/{year}/:
    get:
      description: 'Return all enrollments of a given learning unit year'
      operationId: enrollments_list
      parameters:
        - in: path
          name: acronym
          required: true
          description: The learning unit acronym
          schema:
            type: string
            example: "LABCD1234"
        - in: path
          name: year
          required: true
          description: The learning unit academic year
          schema:
            type: integer
            example: 2021
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-User-FirstName'
        - $ref: '#/components/parameters/X-User-LastName'
        - $ref: '#/components/parameters/X-User-Email'
        - $ref: '#/components/parameters/X-User-GlobalID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - enrollment
  /specific_profile/{student_uuid}/:
    get:
      description: 'Return the specific profile of a student'
      operationId: specific_profile
      parameters:
        - in: path
          name: student_uuid
          required: true
          description: The student uuid
          schema:
            $ref: '#/components/responses/Uuid'
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-User-FirstName'
        - $ref: '#/components/parameters/X-User-LastName'
        - $ref: '#/components/parameters/X-User-Email'
        - $ref: '#/components/parameters/X-User-GlobalID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentSpecificProfile'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - enrollment
components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **Token &lt;token>**
  parameters:
    X-User-FirstName:
      in: header
      name: X-User-FirstName
      schema:
        type: string
      required: false
    X-User-LastName:
      in: header
      name: X-User-LastName
      schema:
        type: string
      required: false
    X-User-Email:
      in: header
      name: X-User-Email
      schema:
        type: string
      required: false
    X-User-GlobalID:
      in: header
      name: X-User-GlobalID
      schema:
        type: string
      required: false
    Accept-Language:
      in: header
      name: Accept-Language
      description: >
        The header advertises which languages the client is able to understand, and which locale variant is preferred. (By languages, we mean natural languages, such as English, and not programming languages.)
      schema:
        $ref: '#/components/schemas/AcceptedLanguageEnum'
      required: false
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    StudentSpecificProfile:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/TypePepsEnum'
        subtype_sport:
          $ref: '#/components/schemas/SportSubtypePepsEnum'
        subtype_disability:
          $ref: '#/components/schemas/DisabilitySubtypePepsEnum'
        guide:
          type: string
          example: "John Doe"
        arrangement_additional_time:
          type: boolean
        arrangement_appropriate_copy:
          type: boolean
        arrangement_other:
          type: boolean
        arrangement_specific_locale:
          type: boolean
        arrangement_comment:
          type: string
          example: "comment"
    Paging:
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
          format: uri
          nullable: true
        previous:
          type: string
          format: uri
          nullable: true
    EnrollmentList:
      allOf:
        - $ref: '#/components/schemas/Paging'
        - type: object
          properties:
            results:
              type: array
              items:
                $ref: '#/components/schemas/Enrollment'
    Enrollment:
      type: object
      properties:
        date_enrollment:
          type: string
          format: date
          example: "2021-09-06"
        enrollment_state:
          type: string
          example: "ENROLLED"
        student_last_name:
          type: string
          example: "Doe"
        student_first_name:
          type: string
          example: "John"
        student_email:
          type: string
          example: "john.doe@mail.xyz"
        student_registration_id:
          type: string
          example: "12345678"
        has_peps:
          type: boolean
        program:
          type: string
          example: "PRGM1BA"
        learning_unit_acronym:
          type: string
          example: "LABCD1234"
    TypePepsEnum:
      type: string
      nullable: true
      enum:
        - NOT_DEFINED
        - DISABILITY
        - SPORT
        - ARTIST
        - ENTREPRENEUR
        - ARRANGEMENT_JURY
        - ""
    SportSubtypePepsEnum:
      type: string
      nullable: true
      enum:
        - PROMISING_ATHLETE_HL
        - PROMISING_ATHLETE
        - ""
    DisabilitySubtypePepsEnum:
      type: string
      nullable: true
      enum:
        - REDUCED_MOBILITY
        - OTHER_DISABILITY
        - ""
    AcceptedLanguageEnum:
      type: string
      enum:
        - 'en'
        - 'fr-be'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
security:
  - Token: []
