from .common import CommonGeneralInformation, UpdateCommonGeneralInformation
from .common_aggregate import CommonAggregateAccessRequirements
from .common_bachelor import CommonBachelorAccessRequirements
from .common_master import CommonMasterAccessRequirements
from .common_master_specialized import CommonMasterSpecializedAccessRequirements
from .publish import publish_common_access_requirements, publish_common_pedagogy
