# Generated by Django 2.2.13 on 2021-05-27 07:45

import django.contrib.postgres.operations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0498_auto_20200124_2055'), ('base', '0499_auto_20200108_1526'), ('base', '0500_create_events_creation_and_end_date_proposition'), ('base', '0501_auto_20200128_1134'), ('base', '0502_auto_20200128_1134'), ('base', '0503_auto_20200131_1104'), ('base', '0504_auto_20200203_1441'), ('base', '0505_update_summary_submission_calendars'), ('base', '0506_remove_prerequisites_whithout_item'), ('base', '0507_auto_20200316_1322'), ('base', '0508_auto_20200325_1013'), ('base', '0509_postgis_extension'), ('base', '0510_auto_20200408_1924')]

    dependencies = [
        ('program_management', '0002_auto_20200124_2055'),
        ('base', '0497_auto_20200108_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningClassYear',
        ),
        django.contrib.postgres.operations.CreateExtension(
            name='postgis',
        ),
    ]
