# Generated by Django 2.2.13 on 2021-05-27 07:46

import base.models.entity_version
import ckeditor.fields
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):
    replaces = [('base', '0511_auto_20200416_1234'), ('base', '0512_cte_manager'), ('base', '0513_auto_20200424_1417'),
                ('base', '0514_auto_20200513_1332'), ('base', '0515_auto_20200519_1649'),
                ('base', '0516_auto_20200602_1440'), ('base', '0517_entityversionaddress'),
                ('base', '0518_auto_20200605_1140'), ('base', '0519_studentspecificprofile'),
                ('base', '0520_update_entityversionaddress'), ('base', '0520_organization_types'),
                ('base', '0521_merge_20200629_0912'), ('base', '0522_entity_external_id_nullable'),
                ('base', '0522_auto_20200703_1051'), ('base', '0523_merge_20200703_1533'),
                ('base', '0524_entityversionaddress'), ('base', '0525_add_more_decimal_co_graduation_coeff'),
                ('base', '0526_unique_together_groupelementyear'), ('base', '0527_auto_20200730_1502'),
                ('base', '0528_adapt_prerequisite_for_versions'), ('base', '0529_auto_20200803_1405'),
                ('base', '0530_auto_20200818_0805'), ('base', '0531_auto_20200902_1459'),
                ('base', '0532_auto_20200903_1108'), ('base', '0533_remove_educationgroupyear_main_teaching_campus'),
                ('base', '0534_auto_20200903_1418'), ('base', '0535_auto_20200908_1239'),
                ('base', '0536_studentspecificprofile_uuid'), ('base', '0537_auto_20200923_0924'),
                ('base', '0538_auto_20201005_1140'), ('base', '0539_auto_20201006_1045'),
                ('base', '0540_prevent_empty_address'), ('base', '0541_auto_20201019_1604'),
                ('base', '0542_delete_organizationaddress'), ('base', '0543_auto_20201120_1040'),
                ('base', '0544_auto_20201027_0930'), ('base', '0545_auto_20201126_1645'),
                ('base', '0546_auto_20201207_1024'), ('base', '0547_replace_obsolet_decree_category'),
                ('base', '0548_auto_20201214_1637'), ('base', '0549_auto_20201215_1249'),
                ('base', '0550_remove_learningcontaineryear_in_charge'), ('base', '0550_auto_20201221_1024'),
                ('base', '0551_merge_20210108_0900'), ('base', '0552_remarks_annualized'),
                ('base', '0553_auto_20210108_1118'), ('base', '0554_remove_in_charge'),
                ('base', '0554_auto_20210111_0939'), ('base', '0555_merge_20210113_0756'),
                ('base', '0556_remove_in_charge_fix'), ('base', '0557_learningunityear_other_remark_english'),
                ('base', '0558_auto_20210115_0827'), ('base', '0559_remove_learningunit_other_remark'),
                ('base', '0560_auto_20210120_0845'), ('base', '0561_auto_20210127_1350'),
                ('base', '0562_auto_20210128_1416'), ('base', '0563_auto_20210201_1051'),
                ('base', '0558_auto_20210202_1029'), ('base', '0564_merge_20210203_1310'),
                ('base', '0565_auto_20210203_1310'), ('base', '0566_fix_link_orders'),
                ('base', '0567_auto_20210211_0843'), ('base', '0568_auto_20210217_1149'),
                ('base', '0569_update_is_mandatory_field_when_empty_skeleton'),
                ('base', '0570_studentspecificprofile_comment'), ('base', '0569_auto_20210225_1350'),
                ('base', '0570_merge_20210303_1036'), ('base', '0571_merge_20210308_1853'),
                ('base', '0572_auto_20210309_1616'), ('base', '0573_auto_20210305_1005'),
                ('base', '0574_auto_20210311_1130'), ('base', '0575_sessionexam_education_group_year'),
                ('base', '0576_populate_not_null_fields'), ('base', '0577_auto_20210201_1741'),
                ('base', '0578_auto_20210316_1447'), ('base', '0579_remove_academiccalendar_academic_year'),
                ('base', '0578_studentspecificprofile_translation'), ('base', '0580_merge_20210317_1414'),
                ('base', '0581_auto_20210317_1620'), ('base', '0582_delete_personentity'),
                ('base', '0583_auto_20210324_0954'), ('base', '0584_auto_20210419_0954'),
                ('base', '0585_auto_20210420_0845'), ('base', '0586_auto_20210510_1835')]

    dependencies = [
        ('dissertation', '0051_auto_20191211_1458'),
        ('reference', '0004_domainisced_is_ares'),
        ('program_management', '0008_auto_20200826_0835'),
        ('base', '0510_auto_20200408_1924'),
        ('program_management', '0004_auto_20200323_1055'),
        ('program_management', '0007_auto_20200424_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupelementyear',
            name='child_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_elements', to='program_management.Element'),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='parent_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_elements', to='program_management.Element'),
        ),
        migrations.AlterUniqueTogether(
            name='groupelementyear',
            unique_together={('parent_element', 'child_element')},
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='education_group_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program_management.EducationGroupVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('learning_unit_year', 'education_group_version')},
        ),
    ]
