# Generated by Django 2.2.13 on 2021-02-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0558_auto_20210202_1029'),
        ('base', '0563_auto_20210201_1051'),
    ]

    operations = [
    ]
