# Generated by Django 2.2.13 on 2021-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0566_fix_link_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='source',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('DISSERTATION', 'Dissertation'), ('INTERNSHIP', 'Internship'), ('CONTINUING_EDUCATION', 'Continuing Education')], default='BASE', max_length=25, null=True),
        ),
    ]
