# Generated by Django 2.2.13 on 2021-02-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0564_auto_20210203_1647'),
        ('base', '0566_fix_link_orders'),
    ]

    operations = [
    ]
