# Generated by Django 2.2.13 on 2021-03-05 13:59

from django.db import migrations
from django.db.models import Q, F
from django.utils import timezone

from education_group.models.group_year import GroupYear


def align_titles(apps, schema_editor):
    problematic_gys = find_problematic_gys()
    print("Problematic EducationGroupYears: {}".format(len(problematic_gys)))
    groups_to_update = []
    for gy in problematic_gys:
        print("\t Changing title of {}-{}".format(gy.partial_acronym, gy.academic_year.year))
        egy = gy.educationgroupversion.offer
        gy.title_fr = egy.title
        gy.title_en = egy.title_english
        gy.changed = timezone.now()
        groups_to_update.append(gy)
    GroupYear.objects.bulk_update(groups_to_update, ['title_fr', 'title_en', 'changed'], batch_size=1000)


def find_problematic_gys():
    return GroupYear.objects.filter(academic_year__year__gte=2019).exclude(
        Q(title_fr=F('educationgroupversion__offer__title')) &
        Q(title_en=F('educationgroupversion__offer__title_english'))
    )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0567_auto_20210211_0843'),
    ]

    operations = [
        migrations.RunPython(align_titles),
    ]
