# Generated by Django 2.2.13 on 2021-02-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0567_auto_20210211_0843'),
    ]

    operations = [
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
               {% autoescape off %}
                 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                 <p>Bonjour,</p>
                 <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                 <p>Rappel sur le démarrage de(s) évenement(s) :</p>
           
                 <div class="w3-responsive">
                     <table cellpadding="10" class="w3-table w3-striped w3-hoverable">
                         <thead>
                             <tr>
                                 <th align="left">Intitulé</th>
                                 <th align="left">Date de début</th>
                                 <th align="left">Date de fin</th>
                             </tr>
                         </thead>
                         <tbody>
                         {% for academic_event in academic_events %}                         
                             <tr>
                                 <td align="left">{{ academic_event.title }}</td>
                                 <td align="left">{{ academic_event.start_date|date:"d/m/Y" }}</td>
                                 <td align="left">
                                    {% if academic_event.end_date %}
                                        {{ academic_event.end_date|date:"d/m/Y" }}
                                    {% else %}
                                        -
                                    {% endif %}
                                 </td>
                             </tr>
                         {% endfor %}
                         </tbody>
                     </table>
                 </div>
               {% endautoescape off %}
               ''',
               '[OSIS] Rappel événement(s) du calendrier académique',
               'calendar_reminder_notice_html',
               'HTML',
               'fr-be'])],
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                {% autoescape off %}
                     <p>Bonjour,</p>
                     <p>Ceci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.</p>
                     <p>Rappel sur le démarrage de(s) évenement(s) :</p>
                    
                     <strong>Intitulé - Date de début - Date de fin</strong><br/>
                     {% for academic_event in academic_events %}
                        {{ academic_event.title }} - {{ academic_event.start_date|date:"d/m/Y" }} - {% if academic_event.end_date %} {{ academic_event.end_date|date:"d/m/Y" }} {% else %} - {% endif %}<br/>
                     {% endfor %}
                {% endautoescape off %}
               ''',
               '[OSIS] Rappel événement(s) du calendrier académique',
               'calendar_reminder_notice_txt',
               'PLAIN',
               'fr-be'])],
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language)"
              " VALUES(%s, %s, %s ,%s ,%s);",
              ['''
              {% autoescape off %}
                 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                 <p>Hello,</p>
                 <p>This is an automatic message generated by the OSIS server &ndash; Please do not reply to this message.</p>
                 <p>Reminder on starting academic event(s) :</p>

                 <div class="w3-responsive">
                 <table cellpadding="10" class="w3-table w3-striped w3-hoverable">
                     <thead>
                         <tr>
                             <th align="left">Title</th>
                             <th align="left">Start date</th>
                             <th align="left">End date</th>
                         </tr>
                     </thead>
                      <tbody>
                     {% for academic_event in academic_events %}                         
                         <tr>
                             <td align="left">{{ academic_event.title }}</td>
                             <td align="left">{{ academic_event.start_date|date:"d/m/Y" }}</td>
                             <td align="left">
                                {% if academic_event.end_date %}
                                    {{ academic_event.end_date|date:"d/m/Y" }}
                                {% else %}
                                    -
                                {% endif %}
                             </td>
                         </tr>
                     {% endfor %}
                     </tbody>
                 </table>
                 </div>
               {% endautoescape off %}
               ''',
               '[OSIS] Remind event(s) academic calendar',
               'calendar_reminder_notice_html',
               'HTML',
               'en'])],
        ),
        migrations.RunSQL(
            [("INSERT INTO osis_common_messagetemplate (template, subject, reference, format, language) "
              "VALUES(%s, %s, %s ,%s ,%s);",
              ['''
                {% autoescape off %}
                    <p>Hello,</p>
                    <p>This is an automatic message generated by the OSIS server &ndash; Please do not reply to this message.</p>
                    <p>Reminder on starting academic event(s) :</p>
    
                     <strong>Title - Start date - End date</strong><br/>
                     {% for academic_event in academic_events %}
                        {{ academic_event.title }} - {{ academic_event.start_date|date:"d/m/Y" }} - {% if academic_event.end_date %} {{ academic_event.end_date|date:"d/m/Y" }} {% else %} - {% endif %}<br/>   
                     {% endfor %}
                 {% endautoescape off %}
                ''',
               '[OSIS] Remind event(s) academic calendar',
               'calendar_reminder_notice_txt',
               'PLAIN',
               'en'])],
        ),
    ]
