# Generated by Django 2.2.13 on 2021-02-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0567_auto_20210211_0843'),
        ('base', '0568_auto_20210210_1406'),
    ]

    operations = [
    ]
