# Generated by Django 2.2.13 on 2021-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0569_update_is_mandatory_field_when_empty_skeleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentspecificprofile',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comment'),
        ),
    ]
