# Generated by Django 2.2.13 on 2021-03-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0569_auto_20210225_1521'),
        ('base', '0569_update_is_mandatory_field_when_empty_skeleton'),
    ]

    operations = [
    ]
