# Generated by Django 2.2.13 on 2021-03-26 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0582_delete_personentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissioncondition',
            options={'permissions': (('change_commonadmissioncondition', 'Can change common access requirements'),)},
        ),
    ]
