# Generated by Django 2.2.13 on 2021-03-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0582_delete_personentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutors'},
        ),
    ]
