# Generated by Django 2.2.13 on 2021-05-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0585_auto_20210420_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupelementyear',
            name='max_credits',
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='min_credits',
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='own_comment',
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='quadrimester_derogation',
        ),
    ]
