# Generated by Django 2.2.13 on 2021-07-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0588_remove_learningcomponentyear_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='code',
        ),
    ]
