# Generated by Django 2.2.13 on 2021-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0588_remove_learningcomponentyear_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='stage_dimona',
            field=models.BooleanField(default=False, verbose_name='Stage - Dimona'),
        ),
    ]
