# Generated by Django 2.2.13 on 2021-07-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0590_set_stage_dimona_for_stage_type'),
    ]

    operations = [
        # Cannot delete organization code field because it's used in partnership
    ]
