# Generated by Django 2.2.13 on 2021-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0591_remove_organization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='english_friendly',
            field=models.BooleanField(default=False, verbose_name='English-friendly'),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='exchange_students',
            field=models.BooleanField(default=True, verbose_name='Exchange students'),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='french_friendly',
            field=models.BooleanField(default=False, verbose_name='French-friendly'),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='individual_loan',
            field=models.BooleanField(default=True, verbose_name='Individual loan'),
        ),
    ]
