# Generated by Django 2.2.13 on 2021-08-20 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def initialize_sex_and_edit_gender_values(apps, schema_editor):
    Person = apps.get_model('base', 'Person')
    persons_to_update = Person.objects.all()
    for person in persons_to_update:
        if person.gender != 'U':
            person.sex = person.gender
            if person.gender == 'M':
                person.gender = 'H'
        else:
            person.gender = 'X'
    Person.objects.bulk_update(persons_to_update, ['sex', 'gender'], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ('reference', '0008_zipcode'),
        ('base', '0591_remove_organization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='birth_persons', to='reference.Country', verbose_name='Birth country'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True,
                                      validators=[django.core.validators.RegexValidator('^[1-9]\\d{3}$')]),
        ),
        migrations.AddField(
            model_name='person',
            name='country_of_citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='reference.Country', verbose_name='Country of citizenship'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name_in_use',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
        migrations.RunPython(initialize_sex_and_edit_gender_values),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('H', 'Male'), ('X', 'Other')], max_length=1,
                                   null=True),
        ),
    ]
