# Generated by Django 2.2.13 on 2021-09-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_unit', '0014_auto_20210604_1537'),
        ('base', '0592_auto_20210812_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunitenrollment',
            name='learning_class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='learning_unit.LearningClassYear'),
        ),
    ]
