# Generated by Django 2.2.13 on 2021-07-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0023_copy_11ba_in_new_model'),
        ('base', '0592_auto_20210719_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerenrollment',
            name='cohort_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education_group.CohortYear'),
        ),
    ]
