# Generated by Django 2.2.13 on 2021-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0593_offerenrollment_cohort_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmanager',
            name='cohort',
            field=models.CharField(choices=[('FIRST_YEAR', 'First year bachelor')], max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='programmanager',
            unique_together={('person', 'education_group', 'cohort')},
        ),
    ]
