# Generated by Django 2.2.13 on 2021-09-09 16:55

from django.db import migrations


def initialize_sex_and_edit_gender_values(apps, schema_editor):
    Person = apps.get_model('base', 'Person')
    persons_to_update = Person.objects.all()
    for person in persons_to_update:
        if person.gender != 'U' and person.gender in ['M', 'F']:
            person.sex = person.gender
            if person.gender == 'M':
                person.gender = 'H'
        else:
            person.gender = 'X'
            person.sex = ''
    Person.objects.bulk_update(persons_to_update, ['sex', 'gender'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0597_auto_20210909_1655'),
    ]

    operations = [
        migrations.RunPython(initialize_sex_and_edit_gender_values),
    ]
