# Generated by Django 2.2.13 on 2021-09-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0023_copy_11ba_in_new_model'),
        ('learning_unit', '0014_auto_20210604_1537'),
        ('base', '0599_auto_20210910_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunitenrollment',
            name='learning_class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_unit.LearningClassYear'),
        ),
        migrations.AddField(
            model_name='offerenrollment',
            name='cohort_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education_group.CohortYear'),
        ),
        migrations.AddField(
            model_name='programmanager',
            name='cohort',
            field=models.CharField(choices=[('FIRST_YEAR', 'First year bachelor')], max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='learningunitenrollment',
            unique_together={('offer_enrollment', 'learning_unit_year', 'learning_class_year', 'enrollment_state')},
        ),
        migrations.AlterUniqueTogether(
            name='programmanager',
            unique_together={('person', 'education_group', 'cohort')},
        ),
    ]
