# Generated by Django 2.2.13 on 2021-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0599_auto_20210910_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
