# Generated by Django 2.2.13 on 2021-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0600_auto_20210914_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
