# Generated by Django 2.2.13 on 2021-09-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0023_copy_11ba_in_new_model'),
        ('base', '0600_auto_20210910_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeryearcalendar',
            name='cohort_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_group.CohortYear'),
        ),
        migrations.AlterUniqueTogether(
            name='offeryearcalendar',
            unique_together={('academic_calendar', 'education_group_year', 'cohort_year')},
        ),
    ]
