# Generated by Django 2.2.13 on 2021-09-21 14:27

from django.db import migrations, models

import osis_document.contrib.fields


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0601_auto_20210914_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, null=True,
                                                         size=1),
        ),
    ]
