# Generated by Django 2.2.13 on 2021-09-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0023_copy_11ba_in_new_model'),
        ('base', '0602_learningunitenrollment_learning_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerenrollment',
            name='cohort_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='education_group.CohortYear'),
        ),
    ]
