# Generated by Django 2.2.13 on 2021-09-21 14:43

from django.db import migrations, models

import osis_document.contrib.fields


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0603_auto_20210921_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, null=True,
                                                         size=1),
        ),
    ]
