# Generated by Django 2.2.13 on 2021-09-23 08:39

from django.db import migrations


def remove_program_manager_with_link_to_11ba(apps, schema_editor):
    """
    Remove program manager with link to 11BA (old structure)
    """
    ProgramManager = apps.get_model("base", "ProgramManager")

    return ProgramManager.objects.filter(
        education_group__educationgroupyear__acronym__icontains="11BA"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0605_create_program_manager_for_11ba'),
    ]

    operations = [
        migrations.RunPython(remove_program_manager_with_link_to_11ba, reverse_code=migrations.RunPython.noop),
    ]
