# Generated by Django 2.2.13 on 2021-09-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0606_populate_exam_enrollments_for_cohort'),
        ('base', '0606_auto_20210923_0839'),
    ]

    operations = [
    ]
