# Generated by Django 2.2.13 on 2021-09-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0607_merge_20210923_1722'),
        ('base', '0604_auto_20210921_1443'),
    ]

    operations = [
    ]
