# Generated by Django 2.2.13 on 2021-09-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0603_offerenrollment_cohort_year'),
        ('base', '0608_merge_20210924_1059'),
    ]

    operations = [
    ]
