# Generated by Django 2.2.13 on 2021-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0608_merge_20210924_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaddress',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='postal_box',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='street_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='label',
            field=models.CharField(
                choices=[('RESIDENTIAL', 'Residential'), ('PROFESSIONAL', 'Professional'), ('CONTACT', 'Contact')],
                default='Professional', max_length=20),
        ),
    ]
