# Generated by Django 2.2.13 on 2021-10-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0609_auto_20211011_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunityear',
            name='decimal_scores',
        ),
    ]
