# Generated by Django 2.2.13 on 2021-10-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0613_auto_20211025_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontainer',
            name='uuid',
        ),
    ]
