# Generated by Django 2.2.24 on 2021-10-26 10:27

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0614_remove_learningcontainer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, null=True, size=2),
        ),
    ]
