# Generated by Django 2.2.13 on 2021-11-02 10:51

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0615_auto_20211026_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, null=True, size=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, null=True, size=1),
        ),
    ]
