# Generated by Django 2.2.24 on 2021-11-16 13:17
import datetime

from django.db import migrations, models


def create_payment_notice_academic_calendars(apps, shema_editor):
    AcademicYear = apps.get_model('base', 'academicyear')
    AcademicCalendar = apps.get_model('base', 'academiccalendar')

    academic_year_2021_22 = AcademicYear.objects.get(year=2021)
    ac1 = AcademicCalendar(
        data_year=academic_year_2021_22,
        title="Affichage de l'avertissement de l'avis d'échéance de paiement 1 sur osis-portal",
        start_date=datetime.datetime(2021, 11, 1),
        reference="PAYMENT_NOTICE_1_WARNING"
    )
    ac1.save()
    ac2 = AcademicCalendar(
        data_year=academic_year_2021_22,
        title="Affichage de l'avertissement de l'avis d'échéance de paiement 2 sur osis-portal",
        start_date=datetime.datetime(2021, 11, 1),
        end_date=datetime.datetime(2021, 11, 1),
        reference="PAYMENT_NOTICE_2_WARNING"
    )
    ac2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0615_auto_20211026_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(choices=[('DELIBERATION', 'Deliberation'), ('DISSERTATION_SUBMISSION', 'Dissertation submission'), ('EXAM_ENROLLMENTS', 'Exam enrollments'), ('SCORES_EXAM_DIFFUSION', 'Scores diffusion'), ('SCORES_EXAM_SUBMISSION', 'Scores exam submission'), ('TEACHING_CHARGE_APPLICATION', 'Application for vacant courses'), ('ACCESS_SCHEDULE_CALENDAR', 'Access schedule calendar'), ('COURSE_ENROLLMENT', 'Course enrollment'), ('SUMMARY_COURSE_SUBMISSION', 'Summary course submission'), ('SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE', 'Summary course submission force majeure'), ('EDUCATION_GROUP_SWITCH', 'Education group switch'), ('EDUCATION_GROUP_EDITION', 'Education group edition'), ('EDUCATION_GROUP_EXTENDED_DAILY_MANAGEMENT', 'Education group extended daily management'), ('EDUCATION_GROUP_LIMITED_DAILY_MANAGEMENT', 'Education group limited daily management'), ('LEARNING_UNIT_EXTENDED_PROPOSAL_MANAGEMENT', 'Extended proposal management'), ('LEARNING_UNIT_LIMITED_PROPOSAL_MANAGEMENT', 'Limited proposal management'), ('PAYMENT_NOTICE_1_WARNING', 'Payment notice 1 warning'), ('PAYMENT_NOTICE_2_WARNING', 'Payment notice 2 warning')], db_index=True, max_length=70),
        ),
        migrations.RunPython(create_payment_notice_academic_calendars, elidable=True),
    ]
