# Generated by Django 2.2.24 on 2021-11-30 13:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_administrative_managers(apps, schema_editor):
    Person = apps.get_model("base", "Person")
    CatalogViewer = apps.get_model("base", "CatalogViewer")

    print("Starting migration of administrative managers to Osis-Roles (CatalogViewer)")

    group = _get_and_rename_group(apps)
    administrative_persons = Person.objects.filter(user__groups=group)

    print("{} persons to migrate".format(len(administrative_persons)))

    to_create = []

    for person in administrative_persons:
        to_create.append(CatalogViewer(person=person))

    CatalogViewer.objects.bulk_create(to_create, batch_size=1000)


def _get_and_rename_group(apps):
    Group = apps.get_model("auth", "Group")
    group = Group.objects.get(name='administrative_managers')
    group.name = 'catalog_viewers'
    group.save()
    return group


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0616_auto_20211116_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name': 'Catalog viewer',
                'verbose_name_plural': 'Catalog viewers',
            },
        ),
        migrations.RunPython(migrate_administrative_managers)
    ]
