# Generated by Django 2.2.24 on 2021-12-03 09:37
from django.db import migrations, connection
from django.db.models import Prefetch

from base.models.entity_version import EntityVersion
from base.models.entity_version_address import EntityVersionAddress


def correct_entity_main_address(apps, schema_editor):
    entity_versions = EntityVersion.objects.only_roots().prefetch_related(
        Prefetch(
            'entityversionaddress_set',
            queryset=EntityVersionAddress.objects.all().select_related('country')
        )
    )
    for entity_version in entity_versions:
        if len(entity_version.entityversionaddress_set.all()) == 1:
            with connection.cursor() as cursor:
                sql = "update base_entityversionaddress set is_main=True where id = {}".format(
                    entity_version.entityversionaddress_set.all()[0].pk
                )
                cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0616_auto_20211116_1317'),
    ]

    operations = [
        migrations.RunPython(correct_entity_main_address, elidable=True),
    ]
