# Generated by Django 2.2.24 on 2021-12-03 09:37
from django.db import migrations, connection
from django.db.models import Prefetch

from base.models.entity_version_address import EntityVersionAddress


def correct_entity_main_address(apps, schema_editor):
    EntityVersion = apps.get_model('base', 'entityversion')
    entity_versions = EntityVersion.objects.only_roots().prefetch_related(
        Prefetch(
            'entityversionaddress_set',
            queryset=EntityVersionAddress.objects.all().select_related('country')
        )
    )
    for entity_version in entity_versions:
        if len(entity_version.entityversionaddress_set.all()) == 1:
            entity_version_address = entity_version.entityversionaddress_set.all()[0]
            entity_version_address.is_main = True
            entity_version_address.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0616_auto_20211116_1317'),
    ]

    operations = [
        migrations.RunPython(correct_entity_main_address, elidable=True),
    ]
