# Generated by Django 2.2.24 on 2021-12-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0617_catalog_viewer'),
        ('base', '0617_entity_address_is_main_correction'),
    ]

    operations = [
    ]
