# Generated by Django 2.2.24 on 2022-01-13 11:06

from django.db import migrations
from django.db.models import Exists, OuterRef


def delete_tutors_without_attribution(apps, schema_editor):
    Tutor = apps.get_model('base', 'Tutor')
    AttributionNew = apps.get_model('attribution', 'AttributionNew')
    problematic_tutors = Tutor.objects.annotate(
        has_attribution=Exists(
            queryset=AttributionNew.objects.filter(
                tutor_id=OuterRef('pk')
            )
        )
    ).filter(
        has_attribution=False
    )
    print("{} problematic tutors (without attributions)".format(len(problematic_tutors)))
    for tutor in problematic_tutors:
        print("Removing {} {} - {} from tutors group".format(
            tutor.person.first_name,
            tutor.person.last_name,
            tutor.person.global_id
        ))
        tutor.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0618_merge_20211215_1448'),
        ('attribution', '0045_auto_20210318_0949'),
    ]

    operations = [
        migrations.RunPython(delete_tutors_without_attribution)
    ]
