# Generated by Django 2.2.24 on 2022-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0618_merge_20211215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='volume_declared_vacant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True,
                                      verbose_name='volume declared vacant'),
        ),
    ]
