# Generated by Django 2.2.24 on 2022-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0619_auto_20220112_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='civil_state',
            field=models.CharField(blank=True, choices=[('LEGAL_COHABITANT', 'Legal cohabitant'), ('SINGLE', 'Single'),
                                                        ('DIVORCED', 'Divorced'), ('MARRIED', 'Married'),
                                                        ('SEPARATE', 'Separate'), ('WIDOWED', 'Widowed')], default='',
                                   max_length=30),
        ),
    ]
