# Generated by Django 2.2.24 on 2022-01-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0620_auto_20220117_1104'),
        ('base', '0621_remove_tutors_without_attribution'),
    ]

    operations = [
    ]
