# Generated by Django 2.2.24 on 2022-01-28 11:51

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0621_merge_20220120_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='curriculum',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Curriculum'),
        ),
    ]
