# Generated by Django 2.2.24 on 2022-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0622_person_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(choices=[('DELIBERATION', 'Deliberation'), ('DISSERTATION_SUBMISSION', 'Dissertation submission'), ('EXAM_ENROLLMENTS', 'Exam enrollments'), ('SCORES_EXAM_DIFFUSION', 'Scores diffusion'), ('SCORES_EXAM_SUBMISSION', 'Scores exam submission'), ('ATTENDANCE_MARK', 'Attendance mark'), ('TEACHING_CHARGE_APPLICATION', 'Application for vacant courses'), ('ACCESS_SCHEDULE_CALENDAR', 'Access schedule calendar'), ('COURSE_ENROLLMENT', 'Course enrollment'), ('SUMMARY_COURSE_SUBMISSION', 'Summary course submission'), ('SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE', 'Summary course submission force majeure'), ('EDUCATION_GROUP_SWITCH', 'Education group switch'), ('EDUCATION_GROUP_EDITION', 'Education group edition'), ('EDUCATION_GROUP_EXTENDED_DAILY_MANAGEMENT', 'Education group extended daily management'), ('EDUCATION_GROUP_LIMITED_DAILY_MANAGEMENT', 'Education group limited daily management'), ('LEARNING_UNIT_EXTENDED_PROPOSAL_MANAGEMENT', 'Extended proposal management'), ('LEARNING_UNIT_LIMITED_PROPOSAL_MANAGEMENT', 'Limited proposal management'), ('PAYMENT_NOTICE_1_WARNING', 'Payment notice 1 warning'), ('PAYMENT_NOTICE_2_WARNING', 'Payment notice 2 warning')], db_index=True, max_length=70),
        ),
    ]
