# Generated by Django 3.2.12 on 2022-02-11 11:48

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0622_person_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallearningunit',
            name='initial_data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
