# Generated by Django 2.2.13 on 2021-11-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0615_auto_20211026_1027'),
        ('admission', '0002_auto_20211014_1433'),
        ('osis_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_graduation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.AcademicYear', verbose_name='Academic graduation year')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'ordering': ['-academic_graduation_year__year'],
                'unique_together': {('person', 'academic_graduation_year')},
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('BELGIAN_UNIVERSITY', 'Belgian university'), ('FOREIGN_UNIVERSITY', 'Foreign university'), ('BELGIAN_NON_UNIVERSITY_HIGHER_EDUCATION', 'Belgian non-university higher education'), ('FOREIGN_NON_UNIVERSITY_HIGHER_EDUCATION', 'Foreign non-university higher education'), ('OTHER', 'Other')], max_length=50, verbose_name='Course types')),
                ('curriculum_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='osis_profile.CurriculumYear')),
                ('validated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admission.DoctorateAdmission', verbose_name='Experience validated from this accepted admission.')),
            ],
        ),
    ]
