# Generated by Django 2.2.13 on 2021-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignhighschooldiploma',
            name='equivalence',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('PENDING', 'Pending')], max_length=25, null=True, verbose_name='Is this diploma subject to an equivalence decision by the services of the French community of Belgium?'),
        ),
    ]
