# Generated by Django 2.2.13 on 2021-12-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_auto_20211025_1239'),
        ('osis_profile', '0002_foreignhighschooldiploma_equivalence'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_comprehension', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=25, null=True, verbose_name='Please rate your listening comprehension')),
                ('speaking_ability', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=25, null=True, verbose_name='Please rate your speaking ability')),
                ('writing_ability', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=25, null=True, verbose_name='Please rate your writing ability')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reference.Language', verbose_name='Language')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_knowledge', to='base.Person', verbose_name='Person')),
            ],
            options={
                'unique_together': {('person', 'language')},
            },
        ),
    ]
