# Generated by Django 2.2.13 on 2022-01-18 11:35

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osis_profile', '0003_languageknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belgianhighschooldiploma',
            name='course_orientation',
        ),
        migrations.RemoveField(
            model_name='belgianhighschooldiploma',
            name='course_repeat',
        ),
        migrations.AddField(
            model_name='belgianhighschooldiploma',
            name='high_school_diploma',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='High school diploma'),
        ),
        migrations.AddField(
            model_name='belgianhighschooldiploma',
            name='high_school_transcript',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='A transcript or your last year at high school'),
        ),
        migrations.AddField(
            model_name='foreignhighschooldiploma',
            name='high_school_diploma',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='High school diploma'),
        ),
        migrations.AddField(
            model_name='foreignhighschooldiploma',
            name='high_school_diploma_translation',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='A certified translation of your official transcript of marks for your final year of secondary education'),
        ),
        migrations.AddField(
            model_name='foreignhighschooldiploma',
            name='high_school_transcript',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='A transcript or your last year at high school'),
        ),
        migrations.AddField(
            model_name='foreignhighschooldiploma',
            name='high_school_transcript_translation',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='A certified translation of your official transcript of marks for your final year of secondary education'),
        ),
    ]
