# Generated by Django 2.2.13 on 2022-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_profile', '0004_filefields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignhighschooldiploma',
            name='equivalence',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('PENDING', 'Pending')], default='', max_length=25, verbose_name='Is this diploma subject to an equivalence decision by the services of the French community of Belgium?'),
        ),
    ]
