# Generated by Django 2.2.24 on 2022-02-01 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_highschool'),
        ('base', '0622_person_curriculum'),
        ('osis_profile', '0005_equivalence_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.AcademicYear', verbose_name='Academic year')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'ordering': ['-academic_year__year'],
                'unique_together': {('person', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HIGHER_EDUCATION', 'Higher education'), ('OTHER_ACTIVITY', 'Other activity')], max_length=50, verbose_name='Type')),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institute name')),
                ('institute_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institute city')),
                ('institute_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Institute postal code')),
                ('education_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Education name')),
                ('result', models.CharField(blank=True, choices=[('FAILURE', 'Failure'), ('NO_RESULT', 'No result'), ('SUCCESS', 'Success'), ('SUCCESS_WITH_RESIDUAL_CREDITS', 'Success with residual credits')], default='', max_length=50, null=True, verbose_name='Result')),
                ('graduation_year', models.BooleanField(blank=True, null=True, verbose_name='Is it your graduation year?')),
                ('obtained_grade', models.CharField(blank=True, choices=[('GREATER_DISTINCTION', 'Greater distinction'), ('GREAT_DISTINCTION', 'Great distinction'), ('DISTINCTION', 'Distinction'), ('SATISFACTION', 'Satisfaction'), ('SUCCESS_WITHOUT_DISTINCTION', 'Success without distinction'), ('NO_GRADE', 'No grade')], default='', max_length=50, null=True, verbose_name='Obtained grade')),
                ('rank_in_diploma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rank in diploma')),
                ('issue_diploma_date', models.DateField(blank=True, null=True, verbose_name='Issue diploma date')),
                ('credit_type', models.CharField(blank=True, choices=[('EUROPEAN_UNION_CREDITS', 'European Union credits'), ('NON_EUROPEAN_UNION_CREDITS', 'Non European Union credits'), ('SEMESTERS', 'Semesters')], default='', max_length=50, null=True, verbose_name='Credit type')),
                ('entered_credits_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Entered credit number')),
                ('acquired_credits_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Acquired credit number')),
                ('transcript', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Transcript')),
                ('graduate_degree', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Graduate degree')),
                ('access_certificate_after_60_master', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Access certificate after a 60 master')),
                ('dissertation_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dissertation title')),
                ('dissertation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Dissertation score')),
                ('dissertation_summary', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Dissertation summary')),
                ('belgian_education_community', models.CharField(blank=True, choices=[('FRENCH_SPEAKING', 'French-speaking Community of Belgium'), ('FLEMISH_SPEAKING', 'Flemish-speaking Community'), ('GERMAN_SPEAKING', 'German-speaking Community')], default='', max_length=50, null=True, verbose_name='Education community')),
                ('study_system', models.CharField(blank=True, choices=[('CONTINUING_EDUCATION', 'Continuing education'), ('FULL_TIME_EDUCATION', 'Full-time education')], default='', max_length=50, null=True, verbose_name='Study system')),
                ('study_cycle_type', models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor'), ('DOCTORATE', 'Doctorate'), ('MASTER', 'Master'), ('OTHER_HIGHER_EDUCATION', 'Other higher education')], default='', max_length=50, null=True, verbose_name='Study cycle type')),
                ('transcript_translation', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Transcript translation')),
                ('graduate_degree_translation', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Graduate degree translation')),
                ('activity_type', models.CharField(blank=True, choices=[('ILLNESS', 'Illness'), ('INTERNSHIP', 'Internship'), ('OTHER', 'Other'), ('UNEMPLOYMENT', 'Unemployment'), ('VOLUNTEERING', 'Volunteering'), ('WORK', 'Work')], default='', max_length=50, null=True, verbose_name='Activity type')),
                ('other_activity_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other activity type')),
                ('activity_certificate', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, null=True, size=None, verbose_name='Activity certificate')),
                ('activity_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity position')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.Country', verbose_name='Country')),
                ('curriculum_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='osis_profile.CurriculumYear')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Organization', verbose_name='Institute')),
                ('linguistic_regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.Language', verbose_name='Linguistic regime')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.EducationGroupYear', verbose_name='Program')),
            ],
        ),
    ]
